```{r bayesfactor}
bf <- ml.somatic/ml.wbc$marglik
po <- bf
p.tumor <- po/(1+po)

```

Robust to weight parameter in wbc_somatic model:

```{r sensitivity}
gamma <- seq(0.1, 0.9, by=0.1)
wbc.list <- seq_along(gamma) %>%
    map(function(i, gamma){
        params <- list(wbc=wbc_params(1, 500, gamma=gamma[i]),
                       params=plasma_params(1, 10))
        params
    }, gamma=gamma)
A <- wbc.list %>%
    map_dbl(function(p, dat){
        x <- wbc_somatic(dat, p)
        x
    }, dat=dat)
ml.somatic <- A * B
bf <- ml.somatic/ml.wbc
po <- bf
p.tumor <- po/(1+po)
```

Robust to weight parameter in plasma_somatic model:

```{r sensitivity2}
gamma <- seq(0.1, 0.9, by=0.1)
wbc.list <- seq_along(gamma) %>%
    map(function(i, gamma){
        params <- list(wbc=plasma_params(1, 50, gamma=gamma[i]),
                       params=wbc_params(1, 500))
        params
    }, gamma=gamma)
A <- wbc.list %>%
    map_dbl(function(p, dat){
        x <- wbc_somatic(dat, p)
        x
    }, dat=dat)
ml.somatic <- A * B
bf <- ml.somatic/ml.wbc
po <- bf
p.tumor <- po/(1+po)
```



```{r scratch}
## independently sample
##
## Marginal likelihood under somatic model
##
x.p <- rbinom(S, 1, gamma)
x.w <- rbinom(S, 1, eta)
z <- rbeta(S, 1, 10)
theta.p <- theta.w <- rep(NA, S)
theta.p[x.p == 1] <- runif(sum(x.p), 0, 1)
## prior for theta.w is mixture of point mass at zero and beta(1,10)
theta.w <- z*x.w
##theta.w <- rep(0, S)
theta.p[x.p == 0] <- rbeta(sum(x.p==0), y.p+1, n.p-y.p+1)
## not a CTC observation. Then theta should be 0 under somatic model
##theta.w[x.w == 0] <- rep(0, sum(x.w==0))
loglik.p <- dbinom(y.p, n.p, theta.p, log=TRUE)
loglik.w <- dbinom(y.w, n.w, theta.w, log=TRUE)
logprior.p <- dbeta(theta.p, 1, 1, log=TRUE)
logprior.w <- dbeta(theta.w, 1, 10, log=TRUE) ## is this my prior
logg.p <- log(gamma + dbeta(theta.p, y.p + 1, n.p-y.p + 1))
##
logg.w <- log(dbeta(theta.w, 1, 10))
log.integrand <- loglik.p + loglik.w + logprior.p +
    logprior.w - (logg.p - logg.w)
integrand <- exp(log.integrand)
marg.lik <- mean(integrand)
## check that simulated theta is fatter than posterior
tmp <- tibble(importance=theta.p,
              posterior=rbeta(S, y.p+1, n.p-y.p+1)) %>%
    pivot_longer(cols=c("importance", "posterior"),
                 names_to="density",
                 values_to="deviates")
tmp %>%
    ggplot(aes(deviates)) +
    geom_density(aes(color=density)) +
    theme_bw(base_size=16) +
    coord_cartesian(xlim=c(0, 0.05))
##
## Marginal likelihood under WBC model
##  -- again use mixture of unif and posterior for importance density
x <- rbinom(S, 1, gamma)
theta <- rep(NA, S)
theta[x == 1] <- runif(sum(x), 0, 1)
y <- y.p + y.w
n <- n.p + n.w
theta[x == 0] <- rbeta(sum(x==0), y + 1, n - y + 1)
loglik.p <- dbinom(y.p, n.p, theta, log=TRUE)
loglik.w <- dbinom(y.w, n.w, theta, log=TRUE)
logprior <- dbeta(theta, 1, 1, log=TRUE)
logg <- log(gamma + dbeta(theta, y + 1, n-y + 1))
log.integrand <- loglik.p + loglik.w + logprior - logg
integrand <- exp(log.integrand)
marg.lik.w <- mean(integrand)
bf <- marg.lik/marg.lik.w
```

```{r binomial}
## brute force (answer=0.0909)
S <- 50e3
theta <- runif(S, 0, 1)
loglik <- dbinom(2, 10, theta, log=TRUE)
loglik.prior <- loglik + dunif(theta, 0, 1, log=TRUE)
ml <- mean(exp(loglik.prior)) ## 0.0908
ml
##
## importance sampling with mixture of unif(0,1 ) and posterior as importance sampling estimator.  Let gamma denote mixture weight
## choose gamma small enough to make estimator efficient yet large enough to stabilize the estimator
S <- 50e3
gamma <- 0.3
z <- rbinom(S, 1, gamma)
theta <- rep(NA, S)
theta[z==1] <- rbeta(sum(z), 1, 1)
theta[z==0] <- rbeta(sum(z==0), 3, 9)
log.prior <- dunif(theta, 0, 1, log=TRUE)
loglik <- dbinom(2, 10, theta, log=TRUE)
d.is <- log(0.3 + 0.7*dbeta(theta, 3, 9))
result <- loglik + log.prior - d.is
est <- mean(exp(result))
est ## 0.0905
```
